// src/frontend/react/src/App.tsx
import { useCallback, useEffect, useMemo, useState } from "react";

type Product = {
  productId: string;
  name: string;
  description: string;
  price: number;
  isActive?: boolean;
};

type CartItem = {
  productId: string;
  quantity: number;
  unitPrice: number;
};

type UserProfile = {
  userId: string;
  email: string;
  fullName: string;
  createdAt: string;
};

type LoginResponse = {
  accessToken: string;
  refreshToken: string;
  accessTokenExpiresAt: string;
  user: UserProfile;
};

const authStorageKey = "online-store-auth-react";

function newIdempotencyKey(): string {
  if (typeof crypto !== "undefined" && "randomUUID" in crypto) {
    return crypto.randomUUID();
  }
  return `checkout-${Date.now()}`;
}

function newProductId(): string {
  if (typeof crypto !== "undefined" && "randomUUID" in crypto) {
    return crypto.randomUUID();
  }
  return `product-${Date.now()}`;
}

export default function App() {
  const [loginEmail, setLoginEmail] = useState("demo@example.com");
  const [loginPassword, setLoginPassword] = useState("demo-password");
  const [registerEmail, setRegisterEmail] = useState("");
  const [registerPassword, setRegisterPassword] = useState("");
  const [registerFullName, setRegisterFullName] = useState("");
  const [authToken, setAuthToken] = useState<string | null>(null);
  const [refreshToken, setRefreshToken] = useState<string | null>(null);
  const [currentUser, setCurrentUser] = useState<UserProfile | null>(null);
  const [loginBusy, setLoginBusy] = useState(false);
  const [registerBusy, setRegisterBusy] = useState(false);
  const [loginMessage, setLoginMessage] = useState<string | null>(null);
  const [registerMessage, setRegisterMessage] = useState<string | null>(null);
  const [products, setProducts] = useState<Product[]>([]);
  const [cart, setCart] = useState<CartItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [checkoutResult, setCheckoutResult] = useState<unknown>(null);
  const [checkoutBusy, setCheckoutBusy] = useState(false);
  const [isAdminView, setIsAdminView] = useState(false);
  const [adminProducts, setAdminProducts] = useState<Product[]>([]);
  const [adminLoading, setAdminLoading] = useState(false);
  const [newProductName, setNewProductName] = useState("");
  const [newProductDescription, setNewProductDescription] = useState("");
  const [newProductPrice, setNewProductPrice] = useState("0");
  const [adminMessage, setAdminMessage] = useState<string | null>(null);
  const [createBusy, setCreateBusy] = useState(false);

  useEffect(() => {
    try {
      const raw = localStorage.getItem(authStorageKey);
      if (!raw) {
        return;
      }
      const parsed = JSON.parse(raw) as { accessToken?: string; refreshToken?: string; user?: UserProfile };
      if (parsed.accessToken && parsed.refreshToken && parsed.user?.userId) {
        setAuthToken(parsed.accessToken);
        setRefreshToken(parsed.refreshToken);
        setCurrentUser(parsed.user);
        setLoginEmail(parsed.user.email);
      }
    } catch {
      localStorage.removeItem(authStorageKey);
    }
  }, []);

  const persistAuth = useCallback((token: string, nextRefreshToken: string, user: UserProfile) => {
    localStorage.setItem(authStorageKey, JSON.stringify({ accessToken: token, refreshToken: nextRefreshToken, user }));
  }, []);

  const logout = useCallback(() => {
    if (refreshToken) {
      void fetch("/api/users/logout", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ refreshToken }),
      });
    }
    setAuthToken(null);
    setRefreshToken(null);
    setCurrentUser(null);
    setCart([]);
    setLoginMessage("Logged out.");
    localStorage.removeItem(authStorageKey);
  }, [refreshToken]);

  const tryRefreshToken = useCallback(async (): Promise<string | null> => {
    if (!refreshToken) {
      return null;
    }

    const res = await fetch("/api/users/refresh", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ refreshToken }),
    });
    const body = (await res.json().catch(() => ({}))) as Partial<LoginResponse>;
    if (!res.ok || !body.accessToken || !body.refreshToken || !body.user?.userId) {
      return null;
    }

    setAuthToken(body.accessToken);
    setRefreshToken(body.refreshToken);
    setCurrentUser(body.user);
    persistAuth(body.accessToken, body.refreshToken, body.user);
    return body.accessToken;
  }, [persistAuth, refreshToken]);

  const authenticatedFetch = useCallback(async (input: RequestInfo | URL, init?: RequestInit): Promise<Response> => {
    const headers = new Headers(init?.headers ?? {});
    if (authToken && !headers.has("Authorization")) {
      headers.set("Authorization", `Bearer ${authToken}`);
    }

    let response = await fetch(input, { ...init, headers });
    if (response.status !== 401) {
      return response;
    }

    const refreshedToken = await tryRefreshToken();
    if (!refreshedToken) {
      return response;
    }

    const retryHeaders = new Headers(init?.headers ?? {});
    if (!retryHeaders.has("Authorization")) {
      retryHeaders.set("Authorization", `Bearer ${refreshedToken}`);
    }
    response = await fetch(input, { ...init, headers: retryHeaders });
    return response;
  }, [authToken, tryRefreshToken]);

  const login = useCallback(async () => {
    setLoginBusy(true);
    setLoginMessage(null);
    setError(null);
    try {
      const res = await fetch("/api/users/login", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email: loginEmail.trim(), password: loginPassword }),
      });

      const body = (await res.json().catch(() => ({}))) as Partial<LoginResponse> & { error?: string };
      if (!res.ok || !body.accessToken || !body.user?.userId) {
        throw new Error(body.error || "Invalid login credentials.");
      }

      setAuthToken(body.accessToken);
      setRefreshToken(body.refreshToken ?? null);
      setCurrentUser(body.user);
      if (body.refreshToken) {
        persistAuth(body.accessToken, body.refreshToken, body.user);
      }
      setLoginMessage(`Logged in as ${body.user.fullName}`);
      setCart([]);
    } catch (e) {
      setLoginMessage(e instanceof Error ? e.message : "Login failed");
    } finally {
      setLoginBusy(false);
    }
  }, [loginEmail, loginPassword, persistAuth]);

  const register = useCallback(async () => {
    setRegisterBusy(true);
    setRegisterMessage(null);
    try {
      const res = await fetch("/api/users/register", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          email: registerEmail.trim(),
          password: registerPassword,
          fullName: registerFullName.trim(),
        }),
      });

      const body = (await res.json().catch(() => ({}))) as { userId?: string; error?: string };
      if (!res.ok || !body.userId) {
        throw new Error(body.error || "Registration failed.");
      }

      setRegisterMessage("Registration successful. You can now login.");
      setLoginEmail(registerEmail.trim());
      setLoginPassword(registerPassword);
      setRegisterEmail("");
      setRegisterPassword("");
      setRegisterFullName("");
    } catch (e) {
      setRegisterMessage(e instanceof Error ? e.message : "Registration failed");
    } finally {
      setRegisterBusy(false);
    }
  }, [registerEmail, registerFullName, registerPassword]);

  const loadProducts = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await authenticatedFetch("/api/products");
      if (!res.ok) {
        throw new Error(`Products failed: ${res.status}`);
      }
      const data: Product[] = await res.json();
      setProducts(data);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to load products");
    } finally {
      setLoading(false);
    }
  }, [authenticatedFetch]);

  const loadAdminProducts = useCallback(async () => {
    setAdminLoading(true);
    setError(null);
    try {
      const res = await authenticatedFetch("/api/admin/products");
      if (!res.ok) {
        throw new Error(`Admin products failed: ${res.status}`);
      }
      const data: Product[] = await res.json();
      setAdminProducts(data);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to load admin products");
    } finally {
      setAdminLoading(false);
    }
  }, [authenticatedFetch]);

  useEffect(() => {
    void loadProducts();
  }, [loadProducts]);

  useEffect(() => {
    if (!isAdminView) {
      return;
    }
    void loadAdminProducts();
  }, [isAdminView, loadAdminProducts]);

  const persistCart = useCallback(async (items: CartItem[]) => {
    if (!currentUser?.userId) {
      throw new Error("Please login first.");
    }
    const res = await authenticatedFetch(`/api/carts/${currentUser.userId}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ userId: currentUser.userId, items }),
    });
    if (!res.ok) {
      throw new Error(`Cart save failed: ${res.status}`);
    }
  }, [authenticatedFetch, currentUser?.userId]);

  const addToCart = useCallback(
    async (p: Product) => {
      setError(null);
      if (!currentUser?.userId) {
        setError("Please login first.");
        return;
      }
      const next = [...cart];
      const existing = next.find((x) => x.productId === p.productId);
      if (existing) {
        existing.quantity += 1;
      } else {
        next.push({ productId: p.productId, quantity: 1, unitPrice: p.price });
      }
      try {
        await persistCart(next);
        setCart(next);
      } catch (e) {
        setError(e instanceof Error ? e.message : "Cart error");
      }
    },
    [cart, currentUser?.userId, persistCart],
  );

  const checkout = useCallback(async () => {
    setCheckoutBusy(true);
    setCheckoutResult(null);
    setError(null);
    try {
      if (!currentUser?.userId || !authToken) {
        throw new Error("Please login first.");
      }
      if (cart.length === 0) {
        throw new Error("Cart is empty. Add a product first.");
      }

      const res = await authenticatedFetch("/api/checkout", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Idempotency-Key": newIdempotencyKey(),
        },
        body: JSON.stringify({
          userId: currentUser.userId,
          currency: "USD",
          items: cart.map((c) => ({
            productId: c.productId,
            quantity: c.quantity,
            unitPrice: c.unitPrice,
          })),
        }),
      });

      const body = await res.json().catch(() => ({}));
      if (!res.ok) {
        throw new Error(
          (body as { error?: string }).error ||
            `Checkout failed: ${res.status}`,
        );
      }

      setCheckoutResult(body);
      setCart([]);
      await loadProducts();
    } catch (e) {
      setError(e instanceof Error ? e.message : "Checkout error");
    } finally {
      setCheckoutBusy(false);
    }
  }, [authenticatedFetch, cart, currentUser?.userId, loadProducts]);

  const cartSummary = useMemo(
    () => cart.reduce((sum, c) => sum + c.quantity * c.unitPrice, 0),
    [cart],
  );

  const createProduct = useCallback(async () => {
    setCreateBusy(true);
    setError(null);
    setAdminMessage(null);
    try {
      const parsedPrice = Number.parseFloat(newProductPrice);
      if (!Number.isFinite(parsedPrice) || parsedPrice < 0) {
        throw new Error("Price must be a non-negative number.");
      }
      if (!newProductName.trim()) {
        throw new Error("Product name is required.");
      }

      const res = await authenticatedFetch("/api/products", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          productId: newProductId(),
          name: newProductName.trim(),
          description: newProductDescription.trim(),
          price: parsedPrice,
          isActive: true,
        }),
      });
      const body = (await res.json().catch(() => ({}))) as { error?: string };
      if (!res.ok) {
        throw new Error(body.error || `Create product failed: ${res.status}`);
      }

      setAdminMessage("Product created successfully.");
      setNewProductName("");
      setNewProductDescription("");
      setNewProductPrice("0");
      await loadAdminProducts();
      await loadProducts();
    } catch (e) {
      setError(e instanceof Error ? e.message : "Create product failed");
    } finally {
      setCreateBusy(false);
    }
  }, [
    authenticatedFetch,
    loadAdminProducts,
    loadProducts,
    newProductDescription,
    newProductName,
    newProductPrice,
  ]);

  return (
    <main>
      <h1>Online Store (React → HTTPS → Gateway)</h1>
      <p style={{ color: "#475569", marginTop: 0 }}>
        Demo user is pre-seeded in UserService. Cart is stored via CartService
        through the gateway so checkout validation matches the diagram.
      </p>

      {error ? <p className="error">{error}</p> : null}
      <section>
        <h2 style={{ marginTop: 0 }}>Page mode</h2>
        <div className="row-actions">
          <button type="button" disabled={!isAdminView} onClick={() => setIsAdminView(false)}>
            User view (catalog)
          </button>
          <button type="button" disabled={isAdminView} onClick={() => setIsAdminView(true)}>
            Admin view (manage products)
          </button>
        </div>
      </section>

      <section>
        <h2 style={{ marginTop: 0 }}>Login</h2>
        {loginMessage ? <p className="message">{loginMessage}</p> : null}
        <div className="form-grid">
          <label>
            Email
            <input type="email" value={loginEmail} onChange={(e) => setLoginEmail(e.target.value)} />
          </label>
          <label>
            Password
            <input type="password" value={loginPassword} onChange={(e) => setLoginPassword(e.target.value)} />
          </label>
          <div className="row-actions">
            <button type="button" disabled={loginBusy} onClick={() => void login()}>
              {loginBusy ? "Logging in..." : "Login"}
            </button>
            <button type="button" disabled={!authToken} onClick={logout}>
              Logout
            </button>
          </div>
        </div>
        {currentUser ? (
          <p>
            Logged in user: <strong>{currentUser.fullName}</strong> ({currentUser.email})
          </p>
        ) : null}
      </section>

      <section>
        <h2 style={{ marginTop: 0 }}>Register</h2>
        {registerMessage ? <p className="message">{registerMessage}</p> : null}
        <div className="form-grid">
          <label>
            Full name
            <input type="text" value={registerFullName} onChange={(e) => setRegisterFullName(e.target.value)} />
          </label>
          <label>
            Email
            <input type="email" value={registerEmail} onChange={(e) => setRegisterEmail(e.target.value)} />
          </label>
          <label>
            Password
            <input type="password" value={registerPassword} onChange={(e) => setRegisterPassword(e.target.value)} />
          </label>
          <div className="row-actions">
            <button type="button" disabled={registerBusy} onClick={() => void register()}>
              {registerBusy ? "Registering..." : "Register"}
            </button>
          </div>
        </div>
      </section>

      {isAdminView ? (
        <section>
          <h2 style={{ marginTop: 0 }}>Admin - add product</h2>
          {!authToken ? <p>Login required to create products.</p> : null}
          {adminMessage ? <p className="message">{adminMessage}</p> : null}
          <div className="form-grid">
            <label>
              Product name
              <input type="text" value={newProductName} onChange={(e) => setNewProductName(e.target.value)} />
            </label>
            <label>
              Description
              <input
                type="text"
                value={newProductDescription}
                onChange={(e) => setNewProductDescription(e.target.value)}
              />
            </label>
            <label>
              Price
              <input type="number" min="0" step="0.01" value={newProductPrice} onChange={(e) => setNewProductPrice(e.target.value)} />
            </label>
            <div className="row-actions">
              <button type="button" disabled={createBusy || !authToken} onClick={() => void createProduct()}>
                {createBusy ? "Saving..." : "Add product"}
              </button>
              <button type="button" onClick={() => void loadAdminProducts()} disabled={adminLoading}>
                Refresh list
              </button>
            </div>
          </div>

          <h3>Admin product list</h3>
          {adminLoading ? (
            <p>Loading…</p>
          ) : (
            <ul>
              {adminProducts.map((p) => (
                <li key={p.productId}>
                  <span>
                    <strong>{p.name}</strong> — ${p.price.toFixed(2)} {!p.isActive ? "(inactive)" : ""}
                  </span>
                  <span>{p.productId}</span>
                </li>
              ))}
            </ul>
          )}
        </section>
      ) : (
        <section>
          <h2 style={{ marginTop: 0 }}>User - view products</h2>
          {loading ? (
            <p>Loading…</p>
          ) : (
            <ul>
              {products.map((p) => (
                <li key={p.productId}>
                  <span>
                    <strong>{p.name}</strong> — ${p.price.toFixed(2)}
                  </span>
                  <button type="button" onClick={() => void addToCart(p)}>
                    Add to cart
                  </button>
                </li>
              ))}
            </ul>
          )}
        </section>
      )}

      <section>
        <h2 style={{ marginTop: 0 }}>Cart</h2>
        {!authToken ? <p>Login required to persist cart and checkout.</p> : null}
        {cart.length === 0 ? (
          <p>Empty</p>
        ) : (
          <ul>
            {cart.map((c) => (
              <li key={c.productId}>
                <span>{c.productId}</span>
                <span>
                  qty {c.quantity} @ ${c.unitPrice.toFixed(2)}
                </span>
              </li>
            ))}
          </ul>
        )}
        <p>
          <strong>Total:</strong> ${cartSummary.toFixed(2)}
        </p>
        <button type="button" disabled={checkoutBusy} onClick={() => void checkout()}>
          {checkoutBusy ? "Checking out…" : "Checkout"}
        </button>
      </section>

      {checkoutResult ? (
        <section>
          <h2 style={{ marginTop: 0 }}>Last checkout</h2>
          <pre>{JSON.stringify(checkoutResult, null, 2)}</pre>
        </section>
      ) : null}
    </main>
  );
}

// src/frontend/angular/src/app/app.ts
import { JsonPipe, NgFor, NgIf } from '@angular/common';
import { Component } from '@angular/core';

type Product = {
  productId: string;
  name: string;
  description: string;
  price: number;
  isActive?: boolean;
};

type CartItem = {
  productId: string;
  quantity: number;
  unitPrice: number;
};

type UserProfile = {
  userId: string;
  email: string;
  fullName: string;
  createdAt: string;
};

type LoginResponse = {
  accessToken: string;
  refreshToken: string;
  accessTokenExpiresAt: string;
  user: UserProfile;
};

type RegisterResponse = UserProfile & { error?: string };

const authStorageKey = 'online-store-auth';

@Component({
  selector: 'app-root',
  imports: [NgIf, NgFor, JsonPipe],
  templateUrl: './app.html',
  styleUrl: './app.scss'
})
export class App {
  loginEmail = 'demo@example.com';
  loginPassword = 'demo-password';
  registerEmail = '';
  registerPassword = '';
  registerFullName = '';
  loginBusy = false;
  registerBusy = false;
  loginMessage: string | null = null;
  registerMessage: string | null = null;
  refreshToken: string | null = null;
  authToken: string | null = null;
  currentUser: UserProfile | null = null;

  products: Product[] = [];
  cart: CartItem[] = [];
  searchTerm = '';
  selectedQuantities: Partial<Record<string, number>> = {};

  adminProducts: Product[] = [];
  adminLoading = false;
  adminMessage: string | null = null;
  adminForm: Product = {
    productId: '',
    name: '',
    description: '',
    price: 0,
    isActive: true
  };
  editingProductId: string | null = null;

  loading = true;
  error: string | null = null;
  checkoutResult: unknown = null;
  checkoutBusy = false;

  constructor() {
    this.restoreAuthSession();
    void this.loadProducts();
    void this.loadAdminProducts();
  }

  get isAuthenticated(): boolean {
    return !!this.authToken && !!this.currentUser;
  }

  get authHeader(): string | null {
    return this.authToken ? `Bearer ${this.authToken}` : null;
  }

  get activeUserId(): string | null {
    return this.currentUser?.userId ?? null;
  }

  get cartSummary(): number {
    return this.cart.reduce((sum, c) => sum + c.quantity * c.unitPrice, 0);
  }

  async login(): Promise<void> {
    this.loginBusy = true;
    this.loginMessage = null;
    this.error = null;
    try {
      const res = await fetch('/api/users/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          email: this.loginEmail.trim(),
          password: this.loginPassword
        })
      });

      const body = (await res.json().catch(() => ({}))) as Partial<LoginResponse> & { error?: string };
      if (!res.ok || !body.accessToken || !body.user?.userId) {
        throw new Error(body.error || 'Invalid login credentials.');
      }

      this.authToken = body.accessToken;
      this.refreshToken = body.refreshToken ?? null;
      this.currentUser = body.user;
      this.persistAuthSession();
      this.loginMessage = `Logged in as ${body.user.fullName}`;
      this.cart = [];
      await this.loadProducts();
      await this.loadAdminProducts();
    } catch (e) {
      this.loginMessage = e instanceof Error ? e.message : 'Login failed';
    } finally {
      this.loginBusy = false;
    }
  }

  async register(): Promise<void> {
    this.registerBusy = true;
    this.registerMessage = null;
    try {
      const res = await fetch('/api/users/register', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          email: this.registerEmail.trim(),
          password: this.registerPassword,
          fullName: this.registerFullName.trim()
        })
      });

      const body = (await res.json().catch(() => ({}))) as RegisterResponse;
      if (!res.ok || !body.userId) {
        throw new Error(body.error || 'Registration failed.');
      }

      this.registerMessage = 'Registration successful. You can now login.';
      this.loginEmail = this.registerEmail.trim();
      this.loginPassword = this.registerPassword;
      this.registerFullName = '';
      this.registerEmail = '';
      this.registerPassword = '';
    } catch (e) {
      this.registerMessage = e instanceof Error ? e.message : 'Registration failed';
    } finally {
      this.registerBusy = false;
    }
  }

  logout(): void {
    void this.logoutRemote();
    this.authToken = null;
    this.refreshToken = null;
    this.currentUser = null;
    this.cart = [];
    this.loginMessage = 'Logged out.';
    localStorage.removeItem(authStorageKey);
  }

  async loadProducts(): Promise<void> {
    this.loading = true;
    this.error = null;
    try {
      const params = new URLSearchParams();
      if (this.searchTerm.trim()) {
        params.set('q', this.searchTerm.trim());
      }

      const query = params.toString();
      const res = await this.authenticatedFetch(query ? `/api/products?${query}` : '/api/products');
      if (!res.ok) {
        throw new Error(`Products failed: ${res.status}`);
      }
      this.products = (await res.json()) as Product[];
      this.syncSelectedQuantities();
    } catch (e) {
      this.error = e instanceof Error ? e.message : 'Failed to load products';
    } finally {
      this.loading = false;
    }
  }

  async addToCart(product: Product, quantity: number): Promise<void> {
    this.error = null;
    if (!this.activeUserId) {
      this.error = 'Please login first.';
      return;
    }

    if (quantity <= 0) {
      this.error = 'Quantity must be at least 1.';
      return;
    }

    const next = [...this.cart];
    const existing = next.find((x) => x.productId === product.productId);
    if (existing) {
      existing.quantity += quantity;
    } else {
      next.push({
        productId: product.productId,
        quantity,
        unitPrice: product.price
      });
    }

    try {
      await this.persistCart(next);
      this.cart = next;
      this.selectedQuantities[product.productId] = 1;
    } catch (e) {
      this.error = e instanceof Error ? e.message : 'Cart error';
    }
  }

  async checkout(): Promise<void> {
    this.checkoutBusy = true;
    this.checkoutResult = null;
    this.error = null;
    try {
      if (!this.activeUserId || !this.authHeader) {
        throw new Error('Please login first.');
      }

      if (this.cart.length === 0) {
        throw new Error('Cart is empty. Add a product first.');
      }

      const res = await this.authenticatedFetch('/api/checkout', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Idempotency-Key': this.newIdempotencyKey()
        },
        body: JSON.stringify({
          userId: this.activeUserId,
          currency: 'USD',
          items: this.cart.map((c) => ({
            productId: c.productId,
            quantity: c.quantity,
            unitPrice: c.unitPrice
          }))
        })
      });

      const body = (await res.json().catch(() => ({}))) as { error?: string };
      if (!res.ok) {
        throw new Error(body.error || `Checkout failed: ${res.status}`);
      }

      this.checkoutResult = body;
      this.cart = [];
      await this.loadProducts();
    } catch (e) {
      this.error = e instanceof Error ? e.message : 'Checkout error';
    } finally {
      this.checkoutBusy = false;
    }
  }

  formatPrice(value: number): string {
    return value.toFixed(2);
  }

  onQuantityChange(productId: string, raw: string): void {
    const parsed = Number.parseInt(raw, 10);
    this.selectedQuantities[productId] = Number.isFinite(parsed) && parsed > 0 ? parsed : 1;
  }

  async onSearch(): Promise<void> {
    await this.loadProducts();
  }

  startCreateProduct(): void {
    this.editingProductId = null;
    this.adminMessage = null;
    this.adminForm = {
      productId: '',
      name: '',
      description: '',
      price: 0,
      isActive: true
    };
  }

  startEditProduct(product: Product): void {
    this.editingProductId = product.productId;
    this.adminMessage = null;
    this.adminForm = { ...product };
  }

  async saveProduct(): Promise<void> {
    this.adminMessage = null;
    if (!this.isAuthenticated) {
      this.adminMessage = 'Please login first.';
      return;
    }

    if (!this.adminForm.name.trim()) {
      this.adminMessage = 'Product name is required.';
      return;
    }
    if (this.adminForm.price < 0) {
      this.adminMessage = 'Price must be zero or higher.';
      return;
    }

    const isUpdate = !!this.editingProductId;
    const endpoint = isUpdate
      ? `/api/admin/products/${this.editingProductId}`
      : '/api/admin/products';
    const method = isUpdate ? 'PUT' : 'POST';

    const payload: Product = {
      productId: this.editingProductId ?? '',
      name: this.adminForm.name.trim(),
      description: this.adminForm.description.trim(),
      price: Number(this.adminForm.price),
      isActive: this.adminForm.isActive ?? true
    };

    try {
      const res = await this.authenticatedFetch(endpoint, {
        method,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });
      const body = (await res.json().catch(() => ({}))) as { error?: string };
      if (!res.ok) {
        throw new Error(body.error || `Save product failed: ${res.status}`);
      }

      this.adminMessage = isUpdate ? 'Product updated.' : 'Product created.';
      this.startCreateProduct();
      await this.loadAdminProducts();
      await this.loadProducts();
    } catch (e) {
      this.adminMessage = e instanceof Error ? e.message : 'Failed to save product';
    }
  }

  async deactivateProduct(product: Product): Promise<void> {
    this.adminMessage = null;
    if (!this.isAuthenticated) {
      this.adminMessage = 'Please login first.';
      return;
    }

    try {
      const res = await this.authenticatedFetch(`/api/admin/products/${product.productId}`, { method: 'DELETE' });
      if (!res.ok) {
        throw new Error(`Deactivate failed: ${res.status}`);
      }

      this.adminMessage = `Product "${product.name}" deactivated.`;
      await this.loadAdminProducts();
      await this.loadProducts();
    } catch (e) {
      this.adminMessage = e instanceof Error ? e.message : 'Failed to deactivate product';
    }
  }

  private async loadAdminProducts(): Promise<void> {
    if (!this.isAuthenticated) {
      this.adminProducts = [];
      this.adminLoading = false;
      return;
    }

    this.adminLoading = true;
    try {
      const res = await this.authenticatedFetch('/api/admin/products');
      if (!res.ok) {
        throw new Error(`Admin products failed: ${res.status}`);
      }
      this.adminProducts = (await res.json()) as Product[];
    } catch (e) {
      this.adminMessage = e instanceof Error ? e.message : 'Failed to load admin products';
    } finally {
      this.adminLoading = false;
    }
  }

  private syncSelectedQuantities(): void {
    const next: Partial<Record<string, number>> = {};
    for (const p of this.products) {
      next[p.productId] = this.selectedQuantities[p.productId] ?? 1;
    }
    this.selectedQuantities = next;
  }

  private async persistCart(items: CartItem[]): Promise<void> {
    if (!this.activeUserId) {
      throw new Error('Please login first.');
    }

    const res = await this.authenticatedFetch(`/api/carts/${this.activeUserId}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ userId: this.activeUserId, items })
    });
    if (!res.ok) {
      throw new Error(`Cart save failed: ${res.status}`);
    }
  }

  private restoreAuthSession(): void {
    try {
      const raw = localStorage.getItem(authStorageKey);
      if (!raw) {
        return;
      }

      const parsed = JSON.parse(raw) as { accessToken?: string; refreshToken?: string; user?: UserProfile };
      if (!parsed.accessToken || !parsed.user?.userId || !parsed.refreshToken) {
        return;
      }

      this.authToken = parsed.accessToken;
      this.refreshToken = parsed.refreshToken;
      this.currentUser = parsed.user;
      this.loginEmail = parsed.user.email;
    } catch {
      localStorage.removeItem(authStorageKey);
    }
  }

  private persistAuthSession(): void {
    if (!this.authToken || !this.currentUser) {
      return;
    }

    localStorage.setItem(
      authStorageKey,
      JSON.stringify({
        accessToken: this.authToken,
        refreshToken: this.refreshToken,
        user: this.currentUser
      })
    );
  }

  private async authenticatedFetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response> {
    const mergedHeaders = new Headers(init?.headers ?? {});
    if (this.authHeader && !mergedHeaders.has('Authorization')) {
        mergedHeaders.set('Authorization', this.authHeader);
    }

    const response = await fetch(input, { ...init, headers: mergedHeaders });
    if (response.status !== 401 || !this.refreshToken) {
      return response;
    }

    const refreshed = await this.tryRefreshToken();
    if (!refreshed) {
      this.logout();
      return response;
    }

    const retryHeaders = new Headers(init?.headers ?? {});
    if (this.authHeader && !retryHeaders.has('Authorization')) {
      retryHeaders.set('Authorization', this.authHeader);
    }
    return fetch(input, { ...init, headers: retryHeaders });
  }

  private async tryRefreshToken(): Promise<boolean> {
    if (!this.refreshToken) {
      return false;
    }

    const res = await fetch('/api/users/refresh', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ refreshToken: this.refreshToken })
    });
    const body = (await res.json().catch(() => ({}))) as Partial<LoginResponse>;
    if (!res.ok || !body.accessToken || !body.refreshToken || !body.user?.userId) {
      return false;
    }

    this.authToken = body.accessToken;
    this.refreshToken = body.refreshToken;
    this.currentUser = body.user;
    this.persistAuthSession();
    return true;
  }

  private async logoutRemote(): Promise<void> {
    if (!this.refreshToken) {
      return;
    }

    try {
      await fetch('/api/users/logout', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ refreshToken: this.refreshToken })
      });
    } catch {
      // ignore network errors during logout
    }
  }

  private newIdempotencyKey(): string {
    if (typeof crypto !== 'undefined' && 'randomUUID' in crypto) {
      return crypto.randomUUID();
    }

    return `checkout-${Date.now()}`;
  }
}
